### ISSUE TITLE
Proxy's Lib is not listed as a dependency on CurseForge and is not installed automatically via Twitch

### ISSUE THREAD

**Issue by katubug** [MinecraftModDevelopmentMods/spooky-biomes#10]
Not a bug with the mod itself, but I installed the mod via the Twitch launcher, and when I started up the game, it alerted me that a required dependency was not installed (Proxy's Lib).

Just figured I'd let you know. :)

**Comment by ProxyNeko** [comment]
Thanks for the heads up, will fix that in a little bit seems I forgot to edit the build scripts again...

**Comment by ProxyNeko** [comment]
Fixed it now, it should also fix it for future builds hopefully.
