### ISSUE TITLE
crash just by traveling the world, or by startup

### ISSUE THREAD

**Issue by Hydraheads** [MinecraftModDevelopmentMods/spooky-biomes#9]
https://pastebin.com/jDZwpj5Y

**Comment by ProxyNeko** [comment]
I’ll give it a look over later as soon as I can thanks for the report.

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/ugiguwoqot.mccrash

Getting a similar crash.

**Comment by ProxyNeko** [comment]
I’m onto the cause now just trying to get a fix ready. Thanks for the second log though

**Comment by ProxyNeko** [comment]
Fixed in 1.2.0.15 :) Sorry for the wait!
